name: myapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # --- FIREBASE (Aligned Versions to fix Web Crash) ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  
  # --- UTILITIES ---
  image_picker: ^1.1.2
  http: ^1.2.2
  pinput: ^5.0.0
  intl: ^0.19.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  pdf: ^3.10.4
  printing: ^5.11.0
  shared_preferences: ^2.3.2
  
  # --- LOCATION SERVICES ---
  geolocator: ^13.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true